version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: weekly
    reviewers:
      - "Shopify/ruby-dev-exp"
    ignore:
      - dependency-name: "@types/vscode"
